import Route from '@ember/routing/route';

export default Route.extend({
    model() {
        return {
            wholeTable:"各区域份额结果-line chart",
            dashboard:"dashboard",
            areaInfo:{
                title:'区域信息',
                img:'',
                des:'这是潜力较大的区域，是公司最重要的销售区域之一，附近汇集了许多大公司，尽管竞争对手是实力很强的原研厂家B，但是负责该区域的是一位非常有经验的代表，公司的产品市场份额一直保持的较好。这是潜力较大的区域，是公司最重要的销售区域之一，附近汇集了许多大公司，尽管竞争对手是实力很强的原研厂家B，但是负责该区域的是一位非常有经验的代表，公司的产品市场份额一直保持的较好。',
                cards:[
                    {
                        headline:"市场规模",
                        num:"4,383,924"
                    },{
                        headline:"上期销售额",
                        num:"383,924",
                    },{
                        headline:"上期达成率%",
                        num:"89%",
                    },{
                        headline:"下期公司指标",
                        num:"500,000"
                    },{
                        headline:"销售贡献率",
                        num:"17%"
                    }
                ]
            },
            analyze:"有效性分析-",
            action:"行动KPI",
            report:{
                title:"代表业务报告"
            },
            result:{
                title:"公司产品历史销售结果"
            },
            represent:{
                title:"负责代表",
                img:'',
                name:"流川枫",
                feature:"男/28歲 / 研究生 / 英語專業 / 3年工作經驗 / 入職1年",
                advantage:[
                    {
                        adv:"客情关系"
                    },{
                        adv:"学习能力"
                    },{
                        adv:"幻灯演讲"
                    }
                ],
                disadvantage:[
                    {
                        dis:"产品知识",
                    },{
                        dis:"科室会",
                    },{
                        dis:"专业性的拜访",
                    },{
                        dis:"还有啥"
                    }
                ],
                cards:[
                    {
                        headline:"产品知识",
                        num:"8"
                    },{
                        headline:"区域规划管理能力",
                        num:"8"
                    },{
                        headline:"销售能力",
                        num:"9"
                    },{
                        headline:"工作积极性",
                        num:"9"
                    }
                ],
            }
        }
    }
});
